import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineSwatch,
  HiOutlineCodeBracket,
  HiOutlineShoppingBag,
  HiOutlineCursorArrowRays,
  HiOutlineArrowPath,
  HiOutlineBolt,
  HiOutlineCircleStack,
  HiOutlineViewfinderCircle,
  HiOutlineArrowDown,
  HiXMark,
  HiBars3,
  HiOutlineCheck,
  HiOutlineArrowLongRight,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiTypescript,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiPrisma,
  SiAmazon,
  SiStripe,
  SiPaypal,
  SiThreedotjs,
  SiGreensock,
  SiAstro,
  SiPostgresql,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  swatch: HiOutlineSwatch,
  code: HiOutlineCodeBracket,
  bag: HiOutlineShoppingBag,
  cursor: HiOutlineCursorArrowRays,
  refresh: HiOutlineArrowPath,
  bolt: HiOutlineBolt,
  database: HiOutlineCircleStack,
  target: HiOutlineViewfinderCircle,
  arrowDown: HiOutlineArrowDown,
  arrowLongRight: HiOutlineArrowLongRight,
  close: HiXMark,
  menu: HiBars3,
  check: HiOutlineCheck,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  react: SiReact,
  typescript: SiTypescript,
  tailwindcss: SiTailwindcss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  prisma: SiPrisma,
  aws: SiAmazon,
  stripe: SiStripe,
  paypal: SiPaypal,
  threejs: SiThreedotjs,
  gsap: SiGreensock,
  astro: SiAstro,
  postgresql: SiPostgresql,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
